# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  cedreo-homeplanner.com:
    site_hosts:
      - canonical: cedreo-homeplanner.com.dev
        redirects:
          - www.cedreo-homeplanner.com.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_user: wadmin
    admin_email: wab2com@gmail.com
    site_install: false
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
